---
title: "Analysis of Los et al Hazard Experiments"
author: "Hedderik van Rijn"
date: "30 November 2015"
output: html_document
---

```{r}
library(data.table)

## Read raw data files:
dat <- c();

## Read all files in the current directory which match the given pattern:
for (i in list.files("Data",pattern="*csv$",full.names=TRUE)) {
  cat("Working on ",i,"\n")
  tmp <- read.csv(i,header=T)
  ## Only keep the relevant columns: (there is a lot more in the datafile, feel free to have a look if you're looking for something)
  tmp <- tmp[,c("Block","Foreperiod","Location","correct","response","response_time","subject_nr")]
  ## Make names consistent:
  names(tmp) <- c("Block","Foreperiod","Location","Cor","Resp","RT","Subj")
  ## Add "overall" trial number 
  tmp$Trial <- 1:nrow(tmp)  
  ## Add trial number per block:
  tmp$BlockTrial <- rep(1:120,5)
  dat <- rbind(dat,tmp)
}
rm(tmp)
dat <- data.table(dat)
table(dat$Subj)
table(dat$Block)

dat[, Condition := ifelse(Block %in% c(1,3,5), "Uni",
                          ifelse(Block==2, "AntiExp","Exp"))]

dat[,table(Block,Condition,Subj)]
```

```{r, echo=FALSE}
plotdat <- dat[,list(m=mean(RT)),by=list(Foreperiod,Block)]

setkey(plotdat,Foreperiod)
par(mfrow=c(1,5))
for (i in 1:5) {
  plotdat[Block==i ,plot(Foreperiod,m,pch=20,type="b",
                                       xlab="Foreperiod (ms)",ylab="Response time (ms)",
                                       axes=FALSE,ylim=c(300,420),xlim=c(350,1650))]
  axis(1)
  axis(2)
}
```

```{r}
dat[, Half := (BlockTrial <= 60)+1]
plotdat1 <- dat[,list(m=mean(RT)),by=list(Foreperiod,Block)]
plotdat2 <- dat[,list(m=mean(RT)),by=list(Foreperiod,Block,Half)]

setkey(plotdat1,Foreperiod)
setkey(plotdat2,Foreperiod)
par(mfrow=c(1,5))
for (i in 1:5) {
  plotdat1[Block==i,plot(Foreperiod,m,pch=20,type="b",
                                       xlab="Foreperiod (ms)",ylab="Response time (ms)",
                                       axes=FALSE,ylim=c(300,420),xlim=c(350,1650))]
  plotdat2[Block==i & Half==1,lines(Foreperiod,m,pch=21,lty=2,type="b")]
  plotdat2[Block==i & Half==2,lines(Foreperiod,m,pch=21,lty=3,type="b")]
  axis(1)
  axis(2)
}

legend("topright",lty=c(2,3),legend=c("1st half","2nd half"),bty = "n")
```

```{r}

if (!require(hvR)) {
  library(devtools)
  install_github("hedderik/hvR")  # for the hvR::shift function and some   other handy libraries
  require(hvR)
} 

library(lmerTest)
library(RColorBrewer)

dat[,prevFP := hvR::shift(Foreperiod,-1),by=list(Subj,Block)]
dat[,prev2FP := hvR::shift(Foreperiod,-2),by=list(Subj,Block)]
dat[,prev3FP := hvR::shift(Foreperiod,-3),by=list(Subj,Block)]

## Let's just focus on Block 2, anti-exponential:
anadat <- dat[Block==2,]
## Rescale: -.5 .. .5: the estimate for BlockTrial is now the total
## effect (i.e., difference between trial 1 and 120) and all other
## effects are estimated relative to the 60th trial:
anadat[,BlockTrial:=(BlockTrial-60)/120]
lme1 <- lmer(RT ~ BlockTrial + (1 | Subj),data=anadat)
lme2 <- lmer(RT ~ Trial + Foreperiod + (1 | Subj),data=anadat)
lme3a <- lmer(RT ~ Trial + Foreperiod + prevFP + (1 | Subj),data=anadat)
summary(lme3a)

lme3b <- lmer(RT ~ Trial + Foreperiod + prevFP + prev2FP + (1 | Subj),data=anadat)
lme3c <- lmer(RT ~ Trial + Foreperiod + prevFP + prev2FP + prev3FP + (1 | Subj),data=anadat)
```

Let's plot the figures as a function of the previous trial, darkred means that previous trial was 400, red 800, green 1200, and blue 1600 (think: RGB). 

```{r}
plotdat1 <- dat[,list(m=mean(RT)),by=list(Foreperiod,Block)]
plotdat2 <- dat[,list(m=mean(RT)),by=list(Foreperiod,Block,prevFP)]

library(colorspace)

setkey(plotdat1,Foreperiod)
setkey(plotdat2,Foreperiod)
par(mfrow=c(1,5))
cols <- c("darkred","red","darkgreen","blue")
for (i in 1:5) {
  cycle <- 0
  plotdat1[Block==i,plot(Foreperiod,m,pch=20,type="b",
                         xlab="Foreperiod (ms)",ylab="Response time (ms)",
                         axes=FALSE,ylim=c(300,420),xlim=c(350,1650))]
  axis(1)
  axis(2)
  for (j in c(400,800,1200,1600)) {
    cycle <- cycle + 1
    plotdat2[Block==i & prevFP==j,lines(Foreperiod,m,lty=1,type="l",col=cols[cycle])]
  }
}

legend("topright",lty=c(2,3),legend=c("1st half","2nd half"),bty = "n")

```